apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-maxwell
  namespace: data
spec:
  progressDeadlineSeconds: 420
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      k8s-app: dp-maxwell
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: dp-maxwell
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: dp-maxwell
        - name: DB_TYPE
          value: RDS
        - name: KAFKA_SECURITY_PROTOCOL
          value: PLAINTEXT
        - name: ORG
          value: workden91
        - name: TENANT
          value: dp
        - name: KAFKA_ENDPOINT_WITH_PORT
          valueFrom:
            secretKeyRef:
              name: fiber
              key: KAFKA_ENDPOINT_WITH_PORT
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              key: MYSQL_HOST
              name: fiber
        - name: MAXWELL_STORE_SCHEMA_PORT
          valueFrom:
            secretKeyRef:
              key: MAXWELL_STORE_SCHEMA_PORT
              name: fiber
        - name: MAXWELL_STORE_SCHEMA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MAXWELL_STORE_SCHEMA_PASSWORD
              name: fiber
        - name: MAXWELL_STORE_SCHEMA_USER
          valueFrom:
            secretKeyRef:
              key: MAXWELL_STORE_SCHEMA_USER
              name: fiber
        - name: MAXWELL_STORE_SCHEMA_HOST
          valueFrom:
            secretKeyRef:
              key: MAXWELL_STORE_SCHEMA_HOST
              name: fiber
        - name: MAXWELL_STORE_REP_PORT
          valueFrom:
            secretKeyRef:
              key: MAXWELL_STORE_REP_PORT
              name: fiber
        - name: MAXWELL_STORE_REP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MAXWELL_STORE_REP_PASSWORD
              name: fiber
        - name: MAXWELL_STORE_REP_USER
          valueFrom:
            secretKeyRef:
              key: MAXWELL_STORE_REP_USER
              name: fiber
        - name: MAXWELL_STORE_REP_HOST
          valueFrom:
            secretKeyRef:
              key: MAXWELL_STORE_REP_HOST
              name: fiber
        - name: MAXWELL_STORE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MAXWELL_STORE_PASSWORD
              name: fiber
        - name: MAXWELL_STORE_USER
          valueFrom:
            secretKeyRef:
              key: MAXWELL_STORE_USER
              name: fiber
        - name: MAXWELL_STORE_HOST
          valueFrom:
            secretKeyRef:
              key: MAXWELL_STORE_HOST
              name: fiber
        - name: MAXWELL_STORE_DB
          valueFrom:
            secretKeyRef:
              key: MAXWELL_STORE_DB
              name: fiber
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: dp-maxwell
        ports:
        - containerPort: 8080
          name: dp-maxwell
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 1m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        processor: arm
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
